### ISSUE TITLE
White spaces appeared in version 2.9.4

### ISSUE THREAD

**Issue by irmod** [damionx7/Zettel-Notes-Documentation#381]
@damionx7 I can't use Zettel Notes... Any attempt to edit a note results in white spaces...

![White_spaces_02.jpg](https://github.com/user-attachments/assets/a5be1634-b091-4f93-b4da-31795349eb23)

![White_spaces_01.jpg](https://github.com/user-attachments/assets/8ee5c20b-f9c2-4556-ae1b-c1844e99b307)

- Zettel Notes v.2.9.4
- Xiaomi Redmi Note 7 (API 28)
- 64-bit ARMv8-A
- Android 9 (Pie)

**Comment by damionx7** [comment]
I will fix this asap.

**Comment by irmod** [comment]
♥♥♥

**Comment by damionx7** [comment]
I have fixed this issue. Try refreshing the f-droid repository and install v2.9.4 apk again.

**Comment by irmod** [comment]
@damionx7 thank you for your attention and incredible efficiency in solving my issue! You are my hero!!!

After updating to the version from F-Droid (I checked the SHA to avoid re-installing the previous release...), in vertical screen orientation I no longer have white space in Notes List, View Mode, Edit Mode. This is great! I can work in Zettel Notes!

But, to my regret, if I change the screen orientation to landscape, I get a white stripe on the left in Notes List, and in View Mode and Edit Mode, white stripes appear on the left, top and right... 😕

![20250418_202743679.jpg](https://github.com/user-attachments/assets/ba8f89a4-c947-4c04-a988-2d8f22ad543f)

![Screenshot_2025-04-18-20-03-05-334_org.eu.thedoc.zettelnotes.png](https://github.com/user-attachments/assets/6944beaf-d199-4164-a744-199f58f2d96f)

![Screenshot_2025-04-18-20-04-46-976_org.eu.thedoc.zettelnotes.png](https://github.com/user-attachments/assets/e5f4e247-70ac-47e5-888e-9182e445b2dd)

![Screenshot_2025-04-18-20-04-02-348_org.eu.thedoc.zettelnotes.png](https://github.com/user-attachments/assets/5647f4e5-34c2-4eed-81bf-ba916c9f6b09)

![Screenshot_2025-04-18-20-05-20-286_org.eu.thedoc.zettelnotes.png](https://github.com/user-attachments/assets/c0128693-f066-466a-a896-e3715d9de263)

![Screenshot_2025-04-18-20-04-59-279_org.eu.thedoc.zettelnotes.png](https://github.com/user-attachments/assets/df0bce93-798f-49b6-a17b-47aa370b432f)

**Comment by damionx7** [comment]
That is definitely a tricky bug 😃. I will try to fix this.

**Comment by damionx7** [comment]
@irmod Can you test if this issue is fixed in v2.9.5

**Comment by irmod** [comment]
Zettel Notes v3.0.0

@damionx7, the error remains.

https://github.com/user-attachments/assets/7c0341a3-c0a8-43f0-913b-37d04717a629

**Comment by damionx7** [comment]
It will be live in next update.
